---
# Authelia Configuration for Workout Tracker
# See: https://www.authelia.com/configuration/

theme: light
jwt_secret: 'a_very_important_secret'
default_redirection_url: 'https://workout-tracker.yourdomain.com'

server:
  host: 0.0.0.0
  port: 9091
  path: ""
  buffers:
    read: 4096
    write: 4096
  timeouts:
    read: 6s
    write: 6s
    idle: 30s

log:
  level: info
  format: text
  file_path: /config/authelia.log
  keep_stdout: false

totp:
  issuer: 'Workout Tracker'
  period: 30
  skew: 1

authentication_backend:
  password_reset:
    disable: false
  refresh_interval: 5m
  
  # File backend for users (simple setup)
  file:
    path: /config/users_database.yml
    password:
      algorithm: argon2id
      iterations: 1
      salt_length: 16
      parallelism: 8
      memory: 64

access_control:
  default_policy: deny
  rules:
    # Health check - no auth required
    - domain: 'workout-tracker.yourdomain.com'
      policy: bypass
      resources:
        - '^/health$'
    
    # Admin users have full access
    - domain: 'workout-tracker.yourdomain.com'
      policy: two_factor
      subject: 'group:admins'
      
    # Regular users need one factor auth
    - domain: 'workout-tracker.yourdomain.com'
      policy: one_factor
      subject: 'group:users'

session:
  name: 'authelia_session'
  expiration: 1h
  inactivity: 5m
  remember_me_duration: 1M
  
  redis:
    host: redis
    port: 6379
    username: ''
    password: ''
    database_index: 0
    maximum_active_connections: 8
    minimum_idle_connections: 0

regulation:
  max_retries: 3
  find_time: 2m
  ban_time: 5m

storage:
  local:
    path: /config/db.sqlite3

notifier:
  smtp:
    username: 'workout-tracker@yourdomain.com'
    password: 'your-smtp-password'
    host: 'smtp.yourdomain.com'
    port: 587
    sender: 'Workout Tracker <workout-tracker@yourdomain.com>'
    subject: '[Workout Tracker] {title}'
    startup_check_address: 'test@authelia.com'
    disable_require_tls: false
    disable_html_emails: false
    tls:
      skip_verify: false
      minimum_version: 'TLS1.2'

# Alternative: File-based notifier for testing
# notifier:
#   filesystem:
#     filename: /config/notification.txt

identity_providers:
  oidc:
    issuer_private_key: |
      -----BEGIN RSA PRIVATE KEY-----
      # Generate with: openssl genrsa -out private.pem 4096
      # Then paste the contents here
      -----END RSA PRIVATE KEY-----
    
    cors:
      endpoints:
        - authorization
        - token
        - revocation
        - introspection
      allowed_origins_from_client_redirect_uris: true
    
    clients:
      - id: workout-tracker
        description: Workout Tracker PWA
        secret: '$argon2id$v=19$m=65536,t=3,p=4$c2FsdA$hash'
        public: false
        authorization_policy: two_factor
        redirect_uris:
          - 'https://workout-tracker.yourdomain.com/api/oidc/callback'
        scopes:
          - openid
          - profile
          - email
          - groups
        userinfo_signing_algorithm: none
