services:
  workout-tracker:
    build: .
    container_name: workout-tracker
    restart: always
    ports:
      - "8080:8080"
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=${SECRET_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_EXPIRES_MINUTES=${JWT_EXPIRES_MINUTES:-15}
      - DATABASE_PATH=/app/data/workout.db
      - CORS_SUPPORTS_CREDENTIALS=${CORS_SUPPORTS_CREDENTIALS:-false}
      # Rate limiting configuration
      - RATE_LIMIT_DEFAULT=${RATE_LIMIT_DEFAULT:-1000 per hour, 100 per minute}
      - RATE_LIMIT_AUTH_LOGIN=${RATE_LIMIT_AUTH_LOGIN:-5 per minute}
      - RATE_LIMIT_AUTH_REGISTER=${RATE_LIMIT_AUTH_REGISTER:-3 per minute}
      - RATE_LIMIT_STORAGE_URI=${RATE_LIMIT_STORAGE_URI:-memory://}
    volumes:
      - workout_data:/app/data
      - workout_logs:/app/logs
      - workout_backups:/app/backups
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  nginx:
    image: nginx:alpine
    container_name: workout-tracker-nginx
    restart: always
    ports:
      - "8081:80"
      - "443:443"
    volumes:
      - ./deployment/nginx/workout-tracker-docker.conf:/etc/nginx/conf.d/default.conf:ro
      - nginx_logs:/var/log/nginx
    depends_on:
      - workout-tracker

volumes:
  workout_data:
    driver: local
  workout_logs:
    driver: local
  workout_backups:
    driver: local
  nginx_logs:
    driver: local
